name: Generate Latest API Version

on:
  workflow_dispatch:
    inputs:
        version:
          type: string
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_VERSION: ${{ github.event.inputs.version }}
      BRANCH_NAME: release/${{ github.event.inputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Ruby
        uses: ruby/setup-ruby@4ff6f3611a42bc75eee1e5138240eb1613f48c8f # v1.266.0
        with:
          bundler-cache: true

      - name: Create Release Branch
        run: |
          git switch -C $BRANCH_NAME # -C will reset branch if it exists
          git push --set-upstream --force origin $BRANCH_NAME

      - name: Generate Schema
        run: |
          echo "Generating schema for $API_VERSION"
          ./bin/update-schema $API_VERSION
          ./bin/update-version $API_VERSION
          git add .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Generating schema for ${API_VERSION}"
          git push --set-upstream --force origin $BRANCH_NAME
